### ISSUE TITLE
Issue in writablestream with ES 5.5.1

### ISSUE THREAD

**Issue by laroi** [hmalphettes/elasticsearch-streams#19]
Hey,
     I'm trying to write a stream to elasticsearch server (v 5.5.1). I tried running the exact example provided in the read me and I got the following error

```
[illegal_argument_exception] Action/metadata line [1] contains an unknown parameter [index]
```
I manually checked the document passed. It is in the following format

```
{ index: 
     { _id: 'D6B39C14-F259-55B1-853C-E40C0D1656C4',
       index: 'myindex',
       type: 'mytype' } },
  { name: 'Dr. Curtis O. Simmons',
    description: 'Kelucdo vuleko uvege ek dec hotel iv kamiso kom jefmadupi cilok va izaam kuza.',
    address: '449 Awera Ridge',
    _id: 'D6B39C14-F259-55B1-853C-E40C0D1656C4' }
     
```
Any idea what is going on? which version of elasticsearch is supported by this module?

**Comment by laroi** [comment]
Found out that instead of _index_ and _type_, __index_ and __type_ should be passed. Also, __id_ should be removed from the document. Since issue is resolved, please close the issue

**Comment by hmalphettes** [comment]
@laroi thanks! I updated the README here: https://github.com/hmalphettes/elasticsearch-streams/commit/64c220eefa1ca964e3177c968bd0a9b68577d82e
Let me know if I missed something.
