### ISSUE TITLE
Stream ends but process does not exit

### ISSUE THREAD

**Issue by gsf** [hmalphettes/elasticsearch-streams#3]
Hi! Neat stuff here -- thanks for the module. I need a quick sanity check. The following code works, but the process hangs open -- I need to `^C` or add a `process.exit()` in the end listener to stop it after it has finished. Am I missing something obvious?

```js
var ReadableSearch = require('elasticsearch-streams').ReadableSearch;
var client = new require('elasticsearch').Client({
  host: process.argv[2]
});

var scrollExec = function scrollExec(from, callback) {
  if (this.scroll_id) {
    return client.scroll({
      scrollId : this.scroll_id,
      scroll   : '30s'
    }, callback);
  }
  // get a scroll id first
  var self = this;
  client.search({
    index: process.argv[3],
    scroll: '20s',
    size: 42,
    body: {
      query: { match_all: {} }
    }
  }, function(e, resp) {
    self.scroll_id = resp._scroll_id;
    callback(e, resp);
  });
};

var rs = new ReadableSearch(scrollExec);

rs.on('data', function (data) {
  // Do things with the data...
  process.stdout.write('.');
});

rs.on('end', function () {
  console.log('end!');
});
```

**Comment by dweinstein** [comment]
you should try closing your client (`client.close()`) in your `'end'` handler

**Comment by hmalphettes** [comment]
Thanks @gsf! Sorry I missed your issue report somehow.
Thanks @dweinstein for the hint. Added to the readme a mention regarding closing the client:
https://github.com/hmalphettes/elasticsearch-streams/commit/d05d0f4fbe2acf510936891876f6fbbb3b07c591

**Comment by gsf** [comment]
Understood now. My guess was that there was a socket open somewhere, but I wasn't sure if it was in this lib or the client. Thanks for the clarification!

**Comment by dweinstein** [comment]
yeah. see https://github.com/elastic/elasticsearch-js/issues/165 on the ES client and voice your concern :-)
